services:
  # DATABASE
  db:
    image: mysql:8.0
    container_name: mysql-db
    restart: always

    # environment variables sourced from my .env file
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}

    command: --secure-file-priv=/var/lib/mysql-files --local-infile=1

    volumes:
      - mysql_data:/var/lib/mysql
      - ./init-scripts:/docker-entrypoint-initdb.d
      - ./sample-data:/var/lib/mysql-files

    networks:
      - argus-network

    # healthcheck to make sure that dependent services wait until mysql is up and running
    healthcheck:
      test: ["CMD-SHELL", "mysql -h 127.0.0.1 -u root -p$$MYSQL_ROOT_PASSWORD -e 'SELECT 1;'"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 15s

  # CORE ARGUS APP
  app:
    build: .
    container_name: argus-app
    restart: on-failure

    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_HOST=db

    # delay startup or argus app until db healthcheck passes (dependency)
    depends_on:
      db:
        condition: service_healthy

    networks:
      - argus-network

    volumes:
      - .:/argus

  # API SERVICE
  api:
    build: .
    container_name: argus-api
    restart: always

    command: uv run uvicorn src.api.routes:app --host 0.0.0.0 --port 8000

    depends_on:
      db:
        condition: service_healthy

    networks:
      - argus-network

    ports:
      - "8000:8000"

    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_HOST=db

    volumes:
      - .:/argus
      - /argus/.venv # avoids mixing up container and host venvs

# PERSISTENT VOLUMES
volumes:
  mysql_data:


#NETWORKS
networks:
  argus-network:
    name: argus-network
